export const WebsocketTypes = {
  WS_CONNECT: 'WS_CONNECT',
  WS_CONNECTING: 'WS_CONNECTING',
  WS_CONNECTED: 'WS_CONNECTED',
  WS_DISCONNECT: 'WS_DISCONNECT',
  WS_DISCONNECTED: 'WS_DISCONNECTED',
  WS_NEW_MESSAGE: 'WS_NEW_MESSAGE',
}
